package com.qsy.ssm.mapper;

import com.qsy.ssm.model.Advs;
import com.qsy.ssm.model.AdvsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    long countByExample(AdvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int deleteByExample(AdvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int insert(Advs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int insertSelective(Advs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    List<Advs> selectByExample(AdvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    Advs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") Advs record, @Param("example") AdvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int updateByExample(@Param("record") Advs record, @Param("example") AdvsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int updateByPrimaryKeySelective(Advs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advs
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    int updateByPrimaryKey(Advs record);
}