package com.qsy.ssm.model;

import java.util.Date;

public class Advs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.id
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.images
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private String images;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.title
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.create_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.update_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.create_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.update_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Date updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.flag
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Boolean flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advs.ordered
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    private Integer ordered;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.id
     *
     * @return the value of advs.id
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.id
     *
     * @param id the value for advs.id
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.images
     *
     * @return the value of advs.images
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.images
     *
     * @param images the value for advs.images
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.title
     *
     * @return the value of advs.title
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.title
     *
     * @param title the value for advs.title
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.create_date
     *
     * @return the value of advs.create_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.create_date
     *
     * @param createDate the value for advs.create_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.update_date
     *
     * @return the value of advs.update_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.update_date
     *
     * @param updateDate the value for advs.update_date
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.create_user
     *
     * @return the value of advs.create_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.create_user
     *
     * @param createUser the value for advs.create_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.update_user
     *
     * @return the value of advs.update_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Date getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.update_user
     *
     * @param updateUser the value for advs.update_user
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setUpdateUser(Date updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.flag
     *
     * @return the value of advs.flag
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.flag
     *
     * @param flag the value for advs.flag
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advs.ordered
     *
     * @return the value of advs.ordered
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public Integer getOrdered() {
        return ordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advs.ordered
     *
     * @param ordered the value for advs.ordered
     *
     * @mbg.generated Tue Sep 19 19:40:02 CST 2017
     */
    public void setOrdered(Integer ordered) {
        this.ordered = ordered;
    }
}