package com.qsy.ssm.model;

public class ProductCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.id
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.pid
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.name
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.flag
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    private Boolean flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_category.parent
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    private Boolean parent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.id
     *
     * @return the value of product_category.id
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.id
     *
     * @param id the value for product_category.id
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.pid
     *
     * @return the value of product_category.pid
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.pid
     *
     * @param pid the value for product_category.pid
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.name
     *
     * @return the value of product_category.name
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.name
     *
     * @param name the value for product_category.name
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.flag
     *
     * @return the value of product_category.flag
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.flag
     *
     * @param flag the value for product_category.flag
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_category.parent
     *
     * @return the value of product_category.parent
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public Boolean getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_category.parent
     *
     * @param parent the value for product_category.parent
     *
     * @mbg.generated Tue Sep 19 13:40:02 CST 2017
     */
    public void setParent(Boolean parent) {
        this.parent = parent;
    }
}